name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Replace environment variables
        run: |
          sed -i "s/\${WEB3FORMS_ACCESS_KEY}/${{ secrets.WEB3FORMS_ACCESS_KEY }}/g" assets/js/config.js
          sed -i "s/\${CAL_API_KEY}/${{ secrets.CAL_API_KEY }}/g" assets/js/config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .